In [1]:
import numpy as np

In [7]:
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [8]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

#Ans--
'''Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list 
   is a NumPy array object.'''
# printing data types of both variables
print(type(list_)) 
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [9]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.


# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [11]:
#Q3. Considering the following changes in the variable, array_list:
#array_list = np.array(object = list_, dtype = int)
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#array_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.

array_list = np.array(object = list_, dtype = int)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [12]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
np.shape(num_array)

(2, 3)

In [15]:
#(ii) size
np.size(num_array)

6

In [17]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
zero_matrix=np.zeros((3,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?
identity_matrix=np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])